[env]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 1500000
build_flags =
    -DESP32S3
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    M5Cardputer=https://github.com/m5stack/M5Cardputer
    TinyGPSPlus=https://github.com/m5stack/TinyGPSPlus

[env:battery]
build_src_filter = +<battery/>

[env:button]
build_src_filter = +<button/>

[env:display]
build_src_filter = +<display/>

[env:gps]
build_src_filter = +<gps/>

[env:motion]
build_src_filter = +<motion/>

[env:ir]
build_src_filter = +<ir/>

[env:lora]
build_src_filter = +<lora/>

[env:keyboard]
build_src_filter = +<keyboard/>

[env:sd]
build_src_filter = +<sd/>

[env:sound]
build_src_filter = +<sound/>