[env]
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
platform = espressif32@6.7.0
; this is a more up-to-date platform
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
build_flags =
    -DESP32S3
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    M5Cardputer=https://github.com/m5stack/M5Cardputer

[env:8encoder]
build_src_filter = +<8encoder/>

[env:battery]
build_src_filter = +<battery/>

[env:button]
build_src_filter = +<button/>

[env:display]
build_src_filter = +<display/>

[env:gps]
build_src_filter = +<gps/>
lib_deps =
    ${env.lib_deps}
    TinyGPSPlus=https://github.com/m5stack/TinyGPSPlus

[env:motion]
build_src_filter = +<motion/>

[env:ir]
build_src_filter = +<ir/>

[env:lora]
build_src_filter = +<lora/>
lib_deps =
    ${env.lib_deps}
    RadioLib=https://github.com/jgromes/RadioLib

[env:keyboard]
build_src_filter = +<keyboard/>

[env:sd]
build_src_filter = +<sd/>

[env:sound]
build_src_filter = +<sound/>

[env:temp]
build_src_filter = +<temp/>

[env:ble_keyboard]
build_src_filter = +<ble_keyboard/>
build_flags =
    ${env.build_flags}
    -DUSE_NIMBLE
lib_deps =
    ${env.lib_deps}
    h2zero/NimBLE-Arduino @ ^1.4.2
    ESP32 BLE Keyboard=https://github.com/T-vK/ESP32-BLE-Keyboard