[platformio]
default_envs = gps

[base]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
# Shared libraries used by EVERY environment
lib_deps = 
    m5stack/M5Unified

[env:gps]
extends = base
src_filter = +<gps.cpp>
# Merges base libs with GPS-specific ones
lib_deps = 
    ${base.lib_deps}
    https://github.com/m5stack/TinyGPSPlus

[env:lora]
extends = base
src_filter = +<lora.cpp>
# Merges base libs with LoRa-specific ones
lib_deps = 
    ${base.lib_deps}
    jgromes/RadioLib
