name: PlatformIO Build

on:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
            .pio
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build & Publish PlatformIO Project
        env:
          M5_AUTH_TOKEN: ${{ secrets.M5_AUTH_TOKEN }}
        run: ./build_and_publish.sh

      - name: Upload firmware release assets
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.bin
